//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: macdb.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate MacDB_WindowServiceClient, then call methods of this protocol to make API calls.
public protocol MacDB_WindowService {
  func capture(callOptions: CallOptions?, handler: @escaping (MacDB_WindowCapture) -> Void) -> BidirectionalStreamingCall<MacDB_WindowInfo, MacDB_WindowCapture>
}

public final class MacDB_WindowServiceClient: GRPCClient, MacDB_WindowService {
  public let connection: ClientConnection
  public var defaultCallOptions: CallOptions

  /// Creates a client for the MacDB.Window service.
  ///
  /// - Parameters:
  ///   - connection: `ClientConnection` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(connection: ClientConnection, defaultCallOptions: CallOptions = CallOptions()) {
    self.connection = connection
    self.defaultCallOptions = defaultCallOptions
  }

  /// Asynchronous bidirectional-streaming call to Capture.
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func capture(callOptions: CallOptions? = nil, handler: @escaping (MacDB_WindowCapture) -> Void) -> BidirectionalStreamingCall<MacDB_WindowInfo, MacDB_WindowCapture> {
    return self.makeBidirectionalStreamingCall(path: "/MacDB.Window/Capture",
                                               callOptions: callOptions ?? self.defaultCallOptions,
                                               handler: handler)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol MacDB_WindowProvider: CallHandlerProvider {
  func capture(context: StreamingResponseCallContext<MacDB_WindowCapture>) -> EventLoopFuture<(StreamEvent<MacDB_WindowInfo>) -> Void>
}

extension MacDB_WindowProvider {
  public var serviceName: String { return "MacDB.Window" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "Capture":
      return BidirectionalStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return self.capture(context: context)
      }

    default: return nil
    }
  }
}

