//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: macdb.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate MacDBServiceClient, then call methods of this protocol to make API calls.
public protocol MacDBService {
  func watchWindow(_ request: WindowInfo, callOptions: CallOptions?, handler: @escaping (Window) -> Void) -> ServerStreamingCall<WindowInfo, Window>
}

public final class MacDBServiceClient: GRPCClient, MacDBService {
  public let connection: ClientConnection
  public var defaultCallOptions: CallOptions

  /// Creates a client for the MacDB service.
  ///
  /// - Parameters:
  ///   - connection: `ClientConnection` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(connection: ClientConnection, defaultCallOptions: CallOptions = CallOptions()) {
    self.connection = connection
    self.defaultCallOptions = defaultCallOptions
  }

  /// Asynchronous server-streaming call to WatchWindow.
  ///
  /// - Parameters:
  ///   - request: Request to send to WatchWindow.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func watchWindow(_ request: WindowInfo, callOptions: CallOptions? = nil, handler: @escaping (Window) -> Void) -> ServerStreamingCall<WindowInfo, Window> {
    return self.makeServerStreamingCall(path: "/MacDB/WatchWindow",
                                        request: request,
                                        callOptions: callOptions ?? self.defaultCallOptions,
                                        handler: handler)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol MacDBProvider: CallHandlerProvider {
  func watchWindow(request: WindowInfo, context: StreamingResponseCallContext<Window>) -> EventLoopFuture<GRPCStatus>
}

extension MacDBProvider {
  public var serviceName: String { return "MacDB" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "WatchWindow":
      return ServerStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.watchWindow(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

